[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "product_repository"
version = "0.1.0"
description = "Common product repository"
requires-python = ">=3.9"
dependencies = []


